name: XCTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: Run tests iOS
      run: xcodebuild clean test -project QRCodeGenerator.xcodeproj -scheme QRCodeGenerator -destination "platform=iOS Simulator,name=iPhone 11 Pro"
